FROM zenoss/%FROM_IMAGE%

# maintener is redundant since base image is ours as well
#MAINTAINER Zenoss <dev@zenoss.com>

ENV ZENHOME=/opt/zenoss

ADD hubpasswd /opt/zenoss/etc/

ADD install_scripts devimg/component_info /opt/zenoss/install_scripts/
ADD zenpacks_artifact.log /opt/zenoss/log/

RUN /opt/zenoss/install_scripts/zenoss_component_install.sh %INSTALL_OPTIONS%

ADD License.zenoss /opt/zenoss/
ADD global.conf /opt/zenoss/etc
