FROM zenoss/%FROM_IMAGE%

# maintener is redundant since base image is ours as well
#MAINTAINER Zenoss <dev@zenoss.com>

ENV ZENHOME=/opt/zenoss

ADD hubpasswd /opt/zenoss/etc/

ADD install_scripts component_info /opt/zenoss/install_scripts/

RUN /opt/zenoss/install_scripts/zenoss_component_install.sh %INSTALL_OPTIONS%

ADD License.zenoss /opt/zenoss/

# the manifest of zenpacks to install
ADD zenpacks.json /opt/zenoss/install_scripts/
ADD zenpacks_artifact.log /opt/zenoss/log/

# the zenpacks shipped in the images
COPY zenpacks /opt/zenoss/packs/

# Initializes zenoss, creates DB and installs zenpacks...
RUN /opt/zenoss/install_scripts/create_zenoss.sh --no-quickstart
