include ../versions.mk

MATURITY     ?= DEV
BUILD_NUMBER ?= DEV

ifeq ($(TARGET_PRODUCT),)
PRODUCT = $(notdir $(shell pwd))
else
PRODUCT = $(TARGET_PRODUCT)
endif

IMAGE_PROJECT = zenoss

ifeq ($(MATURITY)$(BUILD_NUMBER),DEVDEV)
PRODUCT_IMAGE_TAG = dev
MARIADB_IMAGE_TAG = dev
else
PRODUCT_IMAGE_TAG = $(VERSION)_$(BUILD_NUMBER)_$(MATURITY)
MARIADB_IMAGE_TAG = $(VERSION)_$(BUILD_NUMBER)_$(MATURITY)
endif

ifeq ($(PRODUCT),product-assembly)
$(error error: Could not determine PRODUCT to build)
endif

PRODUCT_BASE_IMAGE_REPO  = $(IMAGE_PROJECT)/product-base
PRODUCT_BASE_IMAGE_ID   ?= $(PRODUCT_BASE_IMAGE_REPO):$(PRODUCT_IMAGE_TAG)

MARIADB_BASE_IMAGE_REPO  = $(IMAGE_PROJECT)/mariadb-base
MARIADB_BASE_IMAGE_ID   ?= $(MARIADB_BASE_IMAGE_REPO):$(MARIADB_IMAGE_TAG)

PRODUCT_IMAGE_REPO  = $(IMAGE_PROJECT)/$(PRODUCT)_$(SHORT_VERSION)
PRODUCT_IMAGE_ID   ?= $(PRODUCT_IMAGE_REPO):$(PRODUCT_IMAGE_TAG)

MARIADB_IMAGE_REPO  = $(IMAGE_PROJECT)/mariadb-$(PRODUCT)
MARIADB_IMAGE_ID   ?= $(MARIADB_IMAGE_REPO):$(MARIADB_IMAGE_TAG)
