FROM zenoss/zenoss-centos-base:%VERSION%.devtools

RUN pip --no-python-version-warning install -U "setuptools<45"

RUN groupadd --gid %GID% builder
RUN useradd --uid %UID% --gid %GID% --comment "" builder
