FROM ubuntu:20.04

LABEL maintainer="Zenoss <dev@zenoss.com>"

ENV TERM=xterm ZENHOME=/opt/zenoss PATH="/opt/zenoss/bin:${PATH}"

RUN groupadd -g 1201 -r mysql \
    && useradd -u 1201 -g mysql -r mysql -d /nonexistent -s /bin/false \
    && groupadd -g %GID% -r zenoss \
    && useradd -u %UID% -g zenoss -r zenoss -s /bin/bash -m -d /home/zenoss  -c "Zenoss Account"

#make sure we don't use multiverse repo
RUN sed -i '/^deb.*multiverse/s/^/#\ /' /etc/apt/sources.list \
    && apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install --no-install-recommends -y \
		bash-completion \
		ca-certificates \
		curl            \
		dnsutils        \
		file            \
		htop            \
		iproute2        \
		iputils-ping    \
		less            \
		lsof            \
		mariadb-server  \
		nano            \
		netcat          \
		net-tools       \
		openssh-client  \
		patch           \
		python2.7       \
		python-mysqldb  \
		strace          \
		sysstat         \
		tcpdump         \
		telnet          \
		tmux            \
		traceroute      \
		tree            \
		unzip           \
		vim-tiny        \
		wget            \
		unzip           \
		zip             \
    && apt-get check \
    && apt-get clean

RUN ln -s /usr/bin/vi /usr/bin/vim; \
    mkdir -p /opt/zenoss/bin /opt/zenoss/log /opt/zenoss/bin/metrics /opt/zenoss/var; \
    rm /etc/mysql/mariadb.conf.d/50-server.cnf

RUN wget -qO- https://bootstrap.pypa.io/get-pip.py | python; \
    pip install --no-cache-dir supervisor requests \
    && ln -s /usr/local/bin/supervisord /bin/supervisord

ADD exported.tar /

RUN touch /var/log/mysqld.log; \
    chown mysql:mysql /var/log/mysqld.log; \
    chown -R zenoss:zenoss /opt/zenoss /home/zenoss

RUN /home/zenoss/initialize_db.sh
