FROM zenoss/%FROM_IMAGE%

# maintener is redundant since base image is ours as well
#MAINTAINER Zenoss <dev@zenoss.com>

ADD licenses.core.html License.zenoss /opt/zenoss/
ADD licenses.core.html /opt/zenoss/Products/ZenUI3/docs/licenses.html

ADD zenpacks.json /opt/zenoss/install_scripts/

COPY downloads/*.egg /opt/zenoss/packs/

RUN /opt/zenoss/install_scripts/create_zenoss.sh


