FROM %FROM_IMAGE%


FROM ubuntu:bionic
MAINTAINER Zenoss <dev@zenoss.com>

ENV TERM=xterm ZENHOME=/opt/zenoss

RUN groupadd -g 1201 -r mysql && useradd -u 1201 -g mysql -r mysql -d /nonexistent -s /bin/false \
    && groupadd -g 1202 -r zenoss && useradd -u 1202 -g zenoss -r zenoss -s /bin/bash -m -d /home/zenoss  -c "Zenoss Account"

#make sure we don't use multiverse repo
RUN sed -i '/^deb.*multiverse/s/^/#\ /' /etc/apt/sources.list \
    && apt-get update -y \
    && apt-get install -y \
    vim-tiny           \
    file               \
    dnsutils           \
    telnet             \
    htop               \
    bash-completion    \
    netcat             \
    openssh-client     \
    zip                \
    traceroute         \
    wget               \
    lsof               \
    curl               \
    nano               \
    tree               \
    strace             \
    tcpdump            \
    net-tools          \
    unzip              \
    sysstat            \
    tmux               \
    iproute2           \
    iputils-ping       \
    less               \
    mariadb-server     \
    python2.7          \
    patch              \
    python-mysqldb     \
    && apt-get clean

 
RUN ln -s /usr/bin/vi /usr/bin/vim; ln -s /usr/bin/python2.7 /usr/bin/python; \
    mkdir -p /opt/zenoss/log /opt/zenoss/bin/metrics; rm /etc/mysql/mariadb.conf.d/50-server.cnf; \
    rm -rf /var/lib/mysql/*

RUN wget -qO- https://bootstrap.pypa.io/get-pip.py | python; \
    pip install --no-cache-dir supervisor requests && \
    ln -s /usr/local/bin/supervisord /bin/supervisord

ADD my.cnf /etc/my.cnf

COPY --from=0 --chown=mysql:mysql /var/lib/mysql /var/lib/mysql
COPY --from=0 /opt/zenoss/bin/metrics/ /opt/zenoss/bin/metrics/
COPY --from=0 /opt/zenoss/bin/quiesce-mariadb.sh /opt/zenoss/bin/
COPY --from=0 /opt/zenoss/etc/global.conf /opt/zenoss/etc/
COPY --from=0 /opt/zenoss/Products/ZenUtils/ZenDB.py /opt/zenoss/Products/ZenUtils/
COPY --from=0 /opt/zenoss/Products/ZenUtils/config.py /opt/zenoss/Products/ZenUtils/

ADD mysqlupgrade.sh /opt/zenoss/bin/mysqlupgrade.sh

RUN touch /var/log/mysqld.log; chown mysql:mysql /var/log/mysqld.log; \
    mkdir -p /opt/zenoss/var; chown -R zenoss:zenoss /opt/zenoss

RUN mysqld_safe & until mysqladmin ping 2>/dev/null; do echo "Waiting for mysql..."; sleep 1; done && mysql_upgrade
