#! /usr/bin/env bash
##############################################################################
# 
# Copyright (C) Zenoss, Inc. 2007, all rights reserved.
# 
# This content is made available according to terms specified in
# License.zenoss under the directory where your Zenoss product is installed.
# 
##############################################################################


# This script is intended to contain database/application settings required
# during zenoss startup and upgrade
#
# Note: it is run by root
#
export ZENHOME=/opt/zenoss
function get_var {
    VAR_NAME=$1

    OUTPUT=`su zenoss  -c "$ZENHOME/bin/zenglobalconf -p $VAR_NAME"`
    if [ $? != 0 ]; then
       exit 1
    fi
    echo $OUTPUT
}

if [ ! -d "$ZENHOME" ]; then
    echo "ZENHOME is not set properly: $ZENHOME"
    exit 1
fi

export ZEP_DB_TYPE="`get_var zep-db-type`"
export ZEP_HOST="`get_var zep-host`"
export ZEP_DB="`get_var zep-db`"
export ZEP_PORT="`get_var zep-port`"
export ZEP_ADMIN_USER="`get_var zep-admin-user`"
export ZEP_ADMIN_PASSWORD="`get_var zep-admin-password`"
export ZEP_USER="`get_var zep-user`"
export ZEP_PASSWORD="`get_var zep-password`"

export ZODB_DB_TYPE=`get_var zodb-db-type`
export ZODB_HOST="`get_var zodb-host`"
export ZODB_DB="`get_var zodb-db`"
export ZODB_PORT="`get_var zodb-port`"
export ZODB_ADMIN_USER="`get_var zodb-admin-user`"
export ZODB_ADMIN_PASSWORD="`get_var zodb-admin-password`"
export ZODB_USER="`get_var zodb-user`"
export ZODB_PASSWORD="`get_var zodb-password`"

export RABBITMQ_HOST="`get_var amqphost`"
export RABBITMQ_SSL="`get_var amqpusessl`"
export RABBITMQ_PORT="`get_var amqpport`"
export RABBITMQ_VHOST="`get_var amqpvhost`"
export RABBITMQ_USER="`get_var amqpuser`"
export RABBITMQ_PASS="`get_var amqppassword`"
