FROM zenoss/%FROM_IMAGE%

# maintener is redundant since base image is ours as well
#MAINTAINER Zenoss <dev@zenoss.com>

ADD zphistory.json licenses.resmgr.html License.zenoss /opt/zenoss/
ADD licenses.resmgr.html /opt/zenoss/Products/ZenUI3/docs/licenses.html

# the manifest of zenpacks to install
ADD zenpacks.json /opt/zenoss/install_scripts/
ADD zenpacks_artifact.log /opt/zenoss/log/

# the zenpacks shipped in the images
COPY zenpacks /opt/zenoss/packs/

# Initializes zenoss, creates DB and installs zenpacks...
RUN /opt/zenoss/install_scripts/create_zenoss.sh

ADD upgrade-resmgr.txt upgrade-resmgr.sh upgrade-impact.txt /root/%SHORT_VERSION%.x/
